parameters:
    # Number of related content displayed per page in the tag view
    eztags.default.tag_view.related_content_list.limit: 10

    # Whether to use tag view page cache or not (Last-Modified based)
    eztags.default.tag_view.cache: true

    # Whether to use TTL cache for tag view page (i.e. Max-Age response header)
    eztags.default.tag_view.ttl_cache: true

    # Default TTL cache value for tag view page
    eztags.default.tag_view.default_ttl: 60

    # Default template used to generate tag view page
    eztags.default.tag_view.template: 'NetgenTagsBundle:tag:view.html.twig'

    # Default pagelayout used in tag view page
    eztags.default.tag_view.pagelayout: 'eZDemoBundle::pagelayout.html.twig'

    # Default path prefix to use when generating tag view links
    # Since it's NOT recommended to use empty path prefix here,
    # it will fallback to /tags/view if not specified
    eztags.default.tag_view.path_prefix: '/tags/view'

    # Enables or disables tag router. It can be disabled for example
    # in legacy admin siteacccess
    eztags.default.routing.enable_tag_router: true

    # Setting that will hold all tag view matcher rules
    eztags.default.tag_view_match: {}

    # Setting that will hold all available edit views
    eztags.default.edit_views: {}

    # Default pagelayout template for admin interface
    eztags.default.admin.pagelayout: 'NetgenTagsBundle:admin:pagelayout.html.twig'
