services:
    eztags.field_type.eztags:
        class: Netgen\TagsBundle\Core\FieldType\Tags\Type
        parent: ezpublish.fieldType
        arguments:
            - "@eztags.api.service.tags"
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    eztags.field_type.eztags.external_storage:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
        arguments:
            - []
            - "@eztags.api.service.tags"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}

    eztags.field_type.eztags.indexable:
        class: Netgen\TagsBundle\Core\FieldType\Tags\SearchField
        tags:
            - {name: ezpublish.fieldType.indexable, alias: eztags}

    eztags.field_type.eztags.form_mapper:
        class: Netgen\TagsBundle\Core\FieldType\Tags\FormMapper
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: eztags }
