parameters:
    ezpublish.fieldType.eztags.class: Netgen\TagsBundle\Core\FieldType\Tags\Type
    ezpublish.fieldType.eztags.externalStorage.class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
    ezpublish.fieldType.indexable.eztags.class: Netgen\TagsBundle\Core\FieldType\Tags\SearchField
    ezpublish.fieldType.eztags.formMapper.class: Netgen\TagsBundle\Core\FieldType\Tags\FormMapper

services:
    ezpublish.fieldType.eztags:
        class: %ezpublish.fieldType.eztags.class%
        parent: ezpublish.fieldType
        arguments:
            - "@ezpublish.api.service.tags"
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    ezpublish.fieldType.eztags.externalStorage:
        class: %ezpublish.fieldType.eztags.externalStorage.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}

    ezpublish.fieldType.indexable.eztags:
        class: %ezpublish.fieldType.indexable.eztags.class%
        tags:
            - {name: ezpublish.fieldType.indexable, alias: eztags}

    ezpublish.fieldType.eztags.formMapper:
        class: %ezpublish.fieldType.eztags.formMapper.class%
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - { name: ez.fieldType.formMapper, fieldType: eztags }
