services:
    ezpublish.fieldType.eztags:
        class: Netgen\TagsBundle\Core\FieldType\Tags\Type
        parent: ezpublish.fieldType
        arguments:
            - "@ezpublish.api.service.tags"
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - {name: ezpublish.fieldType, alias: eztags}

    ezpublish.fieldType.eztags.externalStorage:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler, alias: eztags}

    ezpublish.fieldType.indexable.eztags:
        class: Netgen\TagsBundle\Core\FieldType\Tags\SearchField
        tags:
            - {name: ezpublish.fieldType.indexable, alias: eztags}

    ezpublish.fieldType.eztags.formMapper:
        class: Netgen\TagsBundle\Core\FieldType\Tags\FormMapper
        calls:
            - [setEditViews, [$edit_views;eztags$]]
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: eztags }
