services:
    eztags.forms.tree:
        class: Netgen\TagsBundle\Form\Type\TagTreeType
        arguments:
            - "@ezpublish.api.service.tags"
        tags:
            - { name: form.type }

    eztags.forms.translation_list:
        class: Netgen\TagsBundle\Form\Type\TranslationListType
        arguments:
            - "@ezpublish.api.service.language"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: form.type }
