parameters:
     eztags.forms.translation_list.class: Netgen\TagsBundle\Form\Type\TranslationListType

services:
    eztags.forms.translation_list:
        class: "%eztags.forms.translation_list.class%"
        arguments:
            - "@ezpublish.api.service.language"
        tags:
            - { name: form.type }
