system:
    default:
        edit_views:
            default:
                identifier: Default
                name: field_definition.eztags.settings.edit_view.default
            select:
                identifier: Select
                name: field_definition.eztags.settings.edit_view.select
            tree:
                identifier: Tree
                name: field_definition.eztags.settings.edit_view.tree
