services:
    eztags.api.service.tags:
        alias: eztags.signalslot.service.tags

    eztags.signalslot.service.tags:
        class: Netgen\TagsBundle\Core\SignalSlot\TagsService
        lazy: true
        arguments:
            - "@eztags.api.service.tags.inner"
            - "@ezpublish.signalslot.signal_dispatcher"

    eztags.api.service.tags.inner:
        class: Netgen\TagsBundle\Core\Repository\TagsService
        arguments:
            - "@ezpublish.api.repository"
            - "@eztags.api.persistence_handler.tags"
            - "@ezpublish.spi.persistence.legacy.language.handler"

    # Kept for BC with Tags Bundle 2.x

    ezpublish.api.service.tags:
        alias: eztags.api.service.tags
