services:
    ezpublish.api.service.tags:
        alias: ezpublish.signalslot.service.tags

    ezpublish.signalslot.service.tags:
        class: Netgen\TagsBundle\Core\SignalSlot\TagsService
        lazy: true
        arguments:
            - "@ezpublish.api.service.tags.inner"
            - "@ezpublish.signalslot.signal_dispatcher"

    ezpublish.api.service.tags.inner:
        class: Netgen\TagsBundle\Core\Repository\TagsService
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.api.persistence_handler.tags"
            - "@ezpublish.spi.persistence.legacy.language.handler"
