services:
    # Tags handler
    # We use a factory instead of alias so there's no need setting default storage engine twice
    eztags.api.persistence_handler.tags.factory:
        class: Netgen\TagsBundle\DependencyInjection\Factory\TagsHandlerFactory
        arguments:
            - "@service_container"

    eztags.api.persistence_handler.tags:
        class: Netgen\TagsBundle\SPI\Persistence\Tags\Handler
        factory: ["@eztags.api.persistence_handler.tags.factory", buildTagsHandler]
        arguments:
            - "%ezpublish.api.storage_engine.default%"
