tags:
    read: ~
    dashboard: ~
    id: ~
    view: ~
    add: [Tag]
    addsynonym: ~
    edit: ~
    editsynonym: ~
    delete: ~
    deletesynonym: ~
    makesynonym: ~
    merge: ~
    search: ~
