parameters:
    eztags.rest.controller.tags.class: Netgen\TagsBundle\Core\REST\Server\Controller\Tags

    eztags.rest.output.value_object_visitor.cached_value.class: Netgen\TagsBundle\Core\REST\Server\Output\ValueObjectVisitor\CachedValue
    eztags.rest.output.value_object_visitor.rest_tag.class: Netgen\TagsBundle\Core\REST\Server\Output\ValueObjectVisitor\RestTag
    eztags.rest.output.value_object_visitor.tag_list.class: Netgen\TagsBundle\Core\REST\Server\Output\ValueObjectVisitor\TagList
    eztags.rest.output.value_object_visitor.content_list.class: Netgen\TagsBundle\Core\REST\Server\Output\ValueObjectVisitor\ContentList
    eztags.rest.output.value_object_visitor.created_tag.class: Netgen\TagsBundle\Core\REST\Server\Output\ValueObjectVisitor\CreatedTag

    eztags.rest.input.parser.tag_create.class: Netgen\TagsBundle\Core\REST\Server\Input\Parser\TagCreate
    eztags.rest.input.parser.tag_synonym_create.class: Netgen\TagsBundle\Core\REST\Server\Input\Parser\TagSynonymCreate
    eztags.rest.input.parser.tag_update.class: Netgen\TagsBundle\Core\REST\Server\Input\Parser\TagUpdate

services:
    # Controllers

    eztags.rest.controller.tags:
        class: %eztags.rest.controller.tags.class%
        parent: ezpublish_rest.controller.base
        arguments:
            - "@ezpublish.api.service.tags"

    # Value object visitors

    eztags.rest.output.value_object_visitor.cached_value:
        class: %eztags.rest.output.value_object_visitor.cached_value.class%
        parent: ezpublish_rest.output.value_object_visitor.base
        arguments:
            - "@ezpublish.config.resolver"
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Server\Values\CachedValue }

    eztags.rest.output.value_object_visitor.rest_tag:
        class: %eztags.rest.output.value_object_visitor.rest_tag.class%
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Server\Values\RestTag }

    eztags.rest.output.value_object_visitor.tag_list:
        class: %eztags.rest.output.value_object_visitor.tag_list.class%
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Server\Values\TagList }

    # Reimplemented to allow for specifying custom href to content list in the output
    eztags.rest.output.value_object_visitor.content_list:
        class: %eztags.rest.output.value_object_visitor.content_list.class%
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Server\Values\ContentList }

    eztags.rest.output.value_object_visitor.created_tag:
        class: %eztags.rest.output.value_object_visitor.created_tag.class%
        parent: ezpublish_rest.output.value_object_visitor.base
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Netgen\TagsBundle\Core\REST\Server\Values\CreatedTag }

    # Input parsers

    eztags.rest.input.parser.tag_create:
        class: %eztags.rest.input.parser.tag_create.class%
        parent: ezpublish_rest.input.parser
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagCreate }

    eztags.rest.input.parser.tag_synonym_create:
        class: %eztags.rest.input.parser.tag_synonym_create.class%
        parent: ezpublish_rest.input.parser
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagSynonymCreate }

    eztags.rest.input.parser.tag_update:
        class: %eztags.rest.input.parser.tag_update.class%
        parent: ezpublish_rest.input.parser
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish_rest.parser_tools"
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.TagUpdate }
