services:
    eztags.controller.tag_view:
        class: Netgen\TagsBundle\Controller\TagViewController
        parent: ezpublish.controller.base

    eztags.routing.tag_url_generator:
        class: Netgen\TagsBundle\Routing\Generator\TagUrlGenerator
        parent: ezpublish.url_generator.base
        arguments:
            - "@eztags.api.service.tags"
            - "@router.default"
            - "@ezpublish.config.resolver"

    eztags.routing.tag_router:
        class: Netgen\TagsBundle\Routing\TagRouter
        arguments:
            - "@eztags.api.service.tags"
            - "@eztags.routing.tag_url_generator"
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setConfigResolver, ["@ezpublish.config.resolver"]]
        tags:
            - {name: router, priority: 200}

    eztags.event_listener.routing_listener:
        class: Netgen\TagsBundle\EventListener\RouterListener
        lazy: true
        arguments:
            - "@?logger"
        calls:
            - [setEnableTagRouter, [$routing.enable_tag_router;eztags$]]
        tags:
            - {name: kernel.event_subscriber}

    eztags.pagerfanta.related_content_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\RelatedContentAdapter
        lazy: true
        arguments:
            - "@eztags.api.service.tags"
            - $tag_view.related_content_list.return_content_info;eztags$

    eztags.pagerfanta.children_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\ChildrenTagsAdapter
        arguments:
            - "@eztags.api.service.tags"
