services:
    eztags.controller.tag_view:
        class: Netgen\TagsBundle\Controller\TagViewController
        parent: ezpublish.controller.base

    eztags.routing.tag_url_generator:
        class: Netgen\TagsBundle\Routing\Generator\TagUrlGenerator
        parent: ezpublish.url_generator.base
        arguments:
            - "@eztags.api.service.tags"
            - "@router.default"
            - "@ezpublish.config.resolver"

    eztags.routing.tag_router:
        class: Netgen\TagsBundle\Routing\TagRouter
        lazy: true
        arguments:
            - "@eztags.api.service.tags"
            - "@eztags.routing.tag_url_generator"
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - {name: router, priority: 200}
