parameters:
    eztags.controller.tag_view.class: Netgen\TagsBundle\Controller\TagViewController
    eztags.routing.tag_url_generator.class: Netgen\TagsBundle\Routing\Generator\TagUrlGenerator
    eztags.routing.tag_router.class: Netgen\TagsBundle\Routing\TagRouter
    eztags.event_listener.routing_listener.class: Netgen\TagsBundle\EventListener\RouterListener
    eztags.pagerfanta.related_content_adapter.class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\RelatedContentAdapter

services:
    eztags.controller.tag_view:
        class: %eztags.controller.tag_view.class%
        parent: ezpublish.controller.base

    eztags.routing.tag_url_generator:
        class: %eztags.routing.tag_url_generator.class%
        parent: ezpublish.url_generator.base
        arguments:
            - "@ezpublish.api.service.tags"
            - "@router.default"
            - "@ezpublish.config.resolver"

    eztags.routing.tag_router:
        class: %eztags.routing.tag_router.class%
        arguments:
            - "@ezpublish.api.service.tags"
            - "@eztags.routing.tag_url_generator"
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setConfigResolver, ["@ezpublish.config.resolver"]]
        tags:
            - {name: router, priority: 200}

    eztags.event_listener.routing_listener:
        class: %eztags.event_listener.routing_listener.class%
        lazy: true
        arguments:
            - "@?logger"
        calls:
            - [setEnableTagRouter, [$routing.enable_tag_router;eztags$]]
        tags:
            - {name: kernel.event_subscriber}

    eztags.pagerfanta.related_content_adapter:
        class: %eztags.pagerfanta.related_content_adapter.class%
        arguments:
            - "@ezpublish.api.service.tags"
