services:
    eztags.templating.twig.extension:
        class: Netgen\TagsBundle\Templating\Twig\Extension\NetgenTagsExtension
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.translation_helper"
            - "@ezpublish.api.service.language"
            - "@ezpublish.api.service.content_type"
        tags:
            - { name: twig.extension }
