language: php

cache:
    directories:
        - vendor
        - extension

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0

# test only master (+ pull requests)
branches:
  only:
    - master

# make sure to update composer to latest available version
before_install: composer self-update

# install dependencies
install: composer install --no-dev --prefer-source

# setup requirements for running unit tests
before_script:
  - cp config.php-DEVELOPMENT vendor/ezsystems/ezpublish-kernel/config.php

# execute phpunit as the script command
script:
  - phpunit -d memory_limit=-1 --colors -c phpunit.xml
  - phpunit -d memory_limit=-1 --colors -c phpunit-integration-legacy.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false
