services:
    eztags.api.persistence_handler.tags.cache:
        class: Netgen\TagsBundle\Core\Persistence\Cache\Stash\TagsHandler
        public: false
        arguments:
            - "@ezpublish.cache_pool.spi.cache.decorator"
            - "@eztags.api.persistence_handler.tags.storage"
            - "@ezpublish.spi.persistence.cache.persistenceLogger"
