parameters:
    eztags.admin.controller.base.class: Netgen\TagsBundle\Controller\Admin\Controller
    eztags.admin.controller.dashboard.class: Netgen\TagsBundle\Controller\Admin\DashboardController
    eztags.admin.controller.tag.class: Netgen\TagsBundle\Controller\Admin\TagController
    eztags.admin.controller.synonym.class: Netgen\TagsBundle\Controller\Admin\SynonymController
    eztags.admin.controller.tree.class: Netgen\TagsBundle\Controller\Admin\TreeController

services:
    # Controllers

    eztags.admin.controller.base:
        class: "%eztags.admin.controller.base.class%"
        parent: ezpublish.controller.base
        abstract: true
        calls:
            - [performAccessChecks, []]

    eztags.admin.controller.dashboard:
        class: "%eztags.admin.controller.dashboard.class%"
        parent: eztags.admin.controller.base
        arguments:
            - "@ezpublish.api.service.tags"

    eztags.admin.controller.tag:
        class: "%eztags.admin.controller.tag.class%"
        parent: eztags.admin.controller.base
        arguments:
            - "@ezpublish.api.service.tags"
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.search"
            - "@translator"

    eztags.admin.controller.synonym:
        class: "%eztags.admin.controller.synonym.class%"
        parent: eztags.admin.controller.base
        arguments:
            - "@ezpublish.api.service.tags"
            - "@translator"

    eztags.admin.controller.tree:
            class: "%eztags.admin.controller.tree.class%"
            parent: eztags.admin.controller.base
            arguments:
                - "@ezpublish.api.service.tags"
                - "@translator"
                - "@router"
