services:
    # Controllers

    eztags.admin.controller.base:
        class: Netgen\TagsBundle\Controller\Admin\Controller
        parent: ezpublish.controller.base
        abstract: true
        calls:
            - [performAccessChecks, []]

    eztags.admin.controller.tag:
        class: Netgen\TagsBundle\Controller\Admin\TagController
        parent: eztags.admin.controller.base
        arguments:
            - "@eztags.api.service.tags"
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.search"
            - "@translator"
            - "@eztags.pagerfanta.children_tags_adapter"

    eztags.admin.controller.related_content:
        class: Netgen\TagsBundle\Controller\Admin\RelatedContentController
        parent: eztags.admin.controller.base
        arguments:
            - "@eztags.pagerfanta.related_content_adapter"

    eztags.admin.controller.synonym:
        class: Netgen\TagsBundle\Controller\Admin\SynonymController
        parent: eztags.admin.controller.base
        arguments:
            - "@eztags.api.service.tags"
            - "@translator"

    eztags.admin.controller.tree:
            class: Netgen\TagsBundle\Controller\Admin\TreeController
            parent: eztags.admin.controller.base
            arguments:
                - "@eztags.api.service.tags"
                - "@translator"
                - "@router"
