netgen_tags_admin_root:
    path: /tags/admin
    methods: [GET]
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: netgen_tags_admin_dashboard
        permanent: true
