netgen_tags_admin_tag_show:
    path: /{tagId}
    defaults:
        _controller: eztags.admin.controller.tag:showTagAction
        _method: GET

netgen_tags_admin_tag_add:
    path: /add/{parentId}/{languageCode}
    defaults:
        _controller: eztags.admin.controller.tag:addTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_update:
    path: /{tagId}/update/{languageCode}
    defaults:
        _controller: eztags.admin.controller.tag:updateTagAction
        _method: [GET, POST]

netgen_tags_admin_tag_delete:
    path: /{tagId}/delete
    defaults:
        _controller: eztags.admin.controller.tag:deleteTagAction
        _method: [GET, POST]
