system:
    default:
        javascript:
            files:
                - bundles/netgentags/vendor/jquery/dist/jquery.min.js
                - bundles/netgentags/admin/jstree/js/jstree.min.js
                - bundles/netgentags/admin/js/app.js
