services:
    eztags.templating.admin_global_variable:
        class: Netgen\TagsBundle\Templating\Twig\AdminGlobalVariable
        public: false
        # We need the lazy flag due to usage of dynamic parameters
        lazy: true
        calls:
            - [setPageLayoutTemplate, ["$admin.pagelayout;eztags$"]]

    eztags.templating.twig.extension.admin:
        class: Netgen\TagsBundle\Templating\Twig\Extension\AdminExtension
        public: false
        arguments:
            - "@eztags.templating.admin_global_variable"
        tags:
            - { name: twig.extension }
