services:
    # eZ Tags field type
    eztags.field_type.eztags.converter:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Tags
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: eztags, lazy: true, callback: "::create"}

    eztags.field_type.eztags.storage_gateway:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage\Gateway\LegacyStorage
        arguments:
            - "@ezpublish.spi.persistence.legacy.language.handler"
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: eztags, identifier: LegacyStorage}

    # Legacy Tags handler
    eztags.api.storage_engine.legacy.handler.tags.factory:
        class: Netgen\TagsBundle\ApiLoader\LegacyTagsHandlerFactory
        arguments:
            - "@service_container"

    eztags.api.storage_engine.legacy.handler.tags:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Handler
        factory: ["@eztags.api.storage_engine.legacy.handler.tags.factory", buildLegacyTagsHandler]
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
