services:
    # eZ Tags field type
    eztags.field_type.eztags.converter:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Tags
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: eztags, lazy: true, callback: "::create"}

    eztags.field_type.eztags.storage_gateway:
        alias: eztags.field_type.eztags.storage_gateway.doctrine

    eztags.field_type.eztags.storage_gateway.doctrine:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage\Gateway\DoctrineStorage
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"
            - "@ezpublish.spi.persistence.legacy.language.handler"

    eztags.field_type.eztags.storage_gateway.legacy:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage\Gateway\LegacyStorage
        deprecated: 'Netgen Tags legacy storage gateway (%service_id%) is deprecated in favor of Doctrine storage implementation'
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
            - "@ezpublish.spi.persistence.legacy.language.handler"

    eztags.api.storage_engine.legacy.handler.tags.mapper:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Mapper
        arguments:
            - "@ezpublish.spi.persistence.legacy.language.handler"
            - "@ezpublish.persistence.legacy.language.mask_generator"

    eztags.api.storage_engine.legacy.handler.tags.gateway.inner:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Gateway\DoctrineDatabase
        arguments:
            - "@ezpublish.api.storage_engine.legacy.dbhandler"
            - "@ezpublish.spi.persistence.legacy.language.handler"
            - "@ezpublish.persistence.legacy.language.mask_generator"

    eztags.api.storage_engine.legacy.handler.tags.gateway.exception_conversion:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Gateway\ExceptionConversion
        arguments:
            - "@eztags.api.storage_engine.legacy.handler.tags.gateway.inner"

    eztags.api.storage_engine.legacy.handler.tags:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Handler
        arguments:
            - "@eztags.api.storage_engine.legacy.handler.tags.gateway.exception_conversion"
            - "@eztags.api.storage_engine.legacy.handler.tags.mapper"
