services:
    eztags.platformui.event_listener.set_admin_pagelayout:
        class: Netgen\TagsBundle\PlatformUI\EventListener\SetAdminPageLayoutRequestListener
        arguments:
            - "@eztags.templating.admin_global_variable"
            - "%eztags.platformui.admin.pagelayout%"
        tags:
            - { name: kernel.event_subscriber }

    eztags.platformui.event_listener.redirect_response:
        class: Netgen\TagsBundle\PlatformUI\EventListener\RedirectResponseListener
        tags:
            - { name: kernel.event_subscriber }

    eztags.platformui.application_config.provider:
        class: Netgen\TagsBundle\PlatformUI\ConfigProvider
        lazy: true
        arguments:
            - "@security.authorization_checker"
            - "@router"
            - "@ezpublish.config.resolver"
        tags:
            - {name: ezsystems.platformui.application_config_provider, key: 'netgenTags'}
