services:
    eztags.pagerfanta.related_content_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\RelatedContentAdapter
        public: false
        lazy: true
        arguments:
            - "@eztags.api.service.tags"
            - $tag_view.related_content_list.return_content_info;eztags$

    eztags.pagerfanta.children_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\ChildrenTagsAdapter
        public: false
        arguments:
            - "@eztags.api.service.tags"

    eztags.pagerfanta.view.eztags_admin:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\View\TagsAdminView
        public: false
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, ['@@NetgenTags/admin/pagerfanta.html.twig']]
        tags:
            - {name: pagerfanta.view, alias: eztags_admin}
