services:
    eztags.validator.tag_create_struct:
        class: Netgen\TagsBundle\Validator\Structs\TagCreateStructValidator
        # public: false
        tags:
            - { name: validator.constraint_validator, alias: eztags_tag_create_struct }

    eztags.validator.tag_update_struct:
        class: Netgen\TagsBundle\Validator\Structs\TagUpdateStructValidator
        # public: false
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: eztags_tag_update_struct }

    eztags.validator.synonym_create_struct:
        class: Netgen\TagsBundle\Validator\Structs\SynonymCreateStructValidator
        # public: false
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: eztags_synonym_create_struct }

    eztags.validator.tag:
        class: Netgen\TagsBundle\Validator\TagValidator
        # public: false
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: eztags_tag }

    eztags.validator.language:
        class: Netgen\TagsBundle\Validator\LanguageValidator
        # public: false
        arguments:
            - "@ezpublish.api.service.language"
        tags:
            - { name: validator.constraint_validator, alias: eztags_language }

    eztags.validator.remote_id:
        class: Netgen\TagsBundle\Validator\RemoteIdValidator
        # public: false
        arguments:
            - "@eztags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: eztags_remote_id }
