netgen_tags_admin_dashboard:
    path: /
    defaults:
        _controller: eztags.admin.controller.dashboard:indexAction

netgen_tags_admin_tag:
    resource: "admin/tag.yml"
    prefix: /tag

netgen_tags_admin_synonym:
    resource: "admin/synonym.yml"
    prefix: /synonym

netgen_tags_admin_tree:
    resource: "admin/tree.yml"
    prefix: /tree
