ezpublish_rest_eztags_redirectTag:
    path: /tags
    defaults:
        _controller: eztags.rest.controller.tags:redirectTag
    methods: [GET]

ezpublish_rest_eztags_loadTag:
    path: /tags/{tagPath}
    defaults:
        _controller: eztags.rest.controller.tags:loadTag
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

ezpublish_rest_eztags_loadTagsByKeyword:
    path: /tags/keyword/{keyword}/{language}
    defaults:
        _controller: eztags.rest.controller.tags:loadTagsByKeyword
    methods: [GET]

ezpublish_rest_eztags_loadTagChildren:
    path: /tags/{tagPath}/children
    defaults:
        _controller: eztags.rest.controller.tags:loadTagChildren
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

ezpublish_rest_eztags_loadTagSynonyms:
    path: /tags/{tagPath}/synonyms
    defaults:
        _controller: eztags.rest.controller.tags:loadTagSynonyms
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

ezpublish_rest_eztags_getRelatedContent:
    path: /tags/{tagPath}/content
    defaults:
        _controller: eztags.rest.controller.tags:getRelatedContent
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"
