eztags_rest_redirectTag:
    path: /tags
    defaults:
        _controller: eztags.rest.controller.tags:redirectTag
    methods: [GET]

eztags_rest_loadTag:
    path: /tags/{tagPath}
    defaults:
        _controller: eztags.rest.controller.tags:loadTag
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

eztags_rest_loadTagsByKeyword:
    path: /tags/keyword/{keyword}/{language}
    defaults:
        _controller: eztags.rest.controller.tags:loadTagsByKeyword
    methods: [GET]

eztags_rest_loadTagChildren:
    path: /tags/{tagPath}/children
    defaults:
        _controller: eztags.rest.controller.tags:loadTagChildren
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

eztags_rest_loadTagSynonyms:
    path: /tags/{tagPath}/synonyms
    defaults:
        _controller: eztags.rest.controller.tags:loadTagSynonyms
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"

eztags_rest_getRelatedContent:
    path: /tags/{tagPath}/content
    defaults:
        _controller: eztags.rest.controller.tags:getRelatedContent
    methods: [GET]
    requirements:
        tagPath: "[0-9/]+"
