parameters:
    ezpublish.search.solr.query.content.criterion_visitor.tag_id.class: Netgen\TagsBundle\Core\Search\Solr\Query\Content\CriterionVisitor\Tags\TagId
    ezpublish.search.solr.query.location.criterion_visitor.tag_id.class: Netgen\TagsBundle\Core\Search\Solr\Query\Location\CriterionVisitor\Tags\TagId
    ezpublish.search.solr.query.content.criterion_visitor.tag_keyword.class: Netgen\TagsBundle\Core\Search\Solr\Query\Content\CriterionVisitor\Tags\TagKeyword
    ezpublish.search.solr.query.location.criterion_visitor.tag_keyword.class: Netgen\TagsBundle\Core\Search\Solr\Query\Location\CriterionVisitor\Tags\TagKeyword

services:
    ezpublish.search.solr.query.content.criterion_visitor.tag_id:
        class: %ezpublish.search.solr.query.content.criterion_visitor.tag_id.class%
        arguments:
            - "@ezpublish.search.common.field_name_resolver"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "eztags"
            - "tag_ids"
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}

    ezpublish.search.solr.query.location.criterion_visitor.tag_id:
        class: %ezpublish.search.solr.query.location.criterion_visitor.tag_id.class%
        arguments:
            - "@ezpublish.search.common.field_name_resolver"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "eztags"
            - "tag_ids"
        tags:
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    ezpublish.search.solr.query.content.criterion_visitor.tag_keyword:
        class: %ezpublish.search.solr.query.content.criterion_visitor.tag_keyword.class%
        arguments:
            - "@ezpublish.search.common.field_name_resolver"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "eztags"
            - "tag_keywords"
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}

    ezpublish.search.solr.query.location.criterion_visitor.tag_keyword:
        class: %ezpublish.search.solr.query.location.criterion_visitor.tag_keyword.class%
        arguments:
            - "@ezpublish.search.common.field_name_resolver"
            - "@ezpublish.spi.persistence.content_type_handler"
            - "eztags"
            - "tag_keywords"
        tags:
            - {name: ezpublish.search.solr.query.location.criterion_visitor}
